feat: add conversion from text to list
editor-js/nested-list pull request #13
Opened 2021-03-24 22:34 UTC by evanjmg

Allows a user to convert a paragraph or heading to a list.

2021-03-25 07:41 UTC, neSpecc requested changes
I found that there are some excess dots: 

```
- One
- Two
```

Will become

```
One. . Two.
```



Also, please update a patch version.

2021-03-25 07:41 UTC, neSpecc commented on src/index.js
> +  static joinRecursive(data) {
please write a jsdoc

2021-03-25 09:17 UTC, evanjmg commented
Question - @editorjs/list adds periods. Should we even bother adding periods? What if you have a list with periods? Does it make sense to change the content?

2021-03-25 09:26 UTC, evanjmg commented on src/index.js
> +  static joinRecursive(data) {
updated

2021-03-25 09:34 UTC, neSpecc commented
> Question - @editorjs/list adds periods. Should we even bother adding periods? What if you have a list with periods? Does it make sense to change the content?

Good question. I think we need to start with something and collect feedback from users.

2021-03-30 09:03 UTC, evanjmg commented
@neSpecc  any other changes needed or can this be merged?

2021-06-17 19:29 UTC, dfrankow commented
> @neSpecc any other changes needed or can this be merged?

I have the same question.

2021-07-07 17:01 UTC, talyguryn approved these changes

2021-07-07 17:06 UTC, neSpecc approved these changes

2021-07-07 17:07 UTC, merged