Tools Skeleton initial
editor-js/nested-list pull request #2
Opened 2021-02-24 17:09 UTC by khaydarov

2021-02-24 17:15 UTC, talyguryn requested changes

2021-02-24 17:15 UTC, talyguryn commented on src/index.ts
> +import { BlockTool, BlockToolConstructorOptions } from '../../../../types/tools/block-tool';
are these paths valid?

2021-02-25 20:55 UTC, neSpecc reviewed
Ready to approve. We need to create a release branch and target this PR to that branch.

2021-02-25 21:08 UTC, talyguryn approved these changes

2021-02-26 09:55 UTC, neSpecc approved these changes

2021-02-26 12:40 UTC, merged